apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: timescaledb-daily-backup
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: timescaledb-cluster-pg15

