apiVersion: v1
kind: Secret
metadata:
  name: app-user  
  namespace: default      
type: kubernetes.io/basic-auth 
data:
  # myuser
  username: bXl1c2Vy
  # StrongPassword123!
  password: U3Ryb25nUGFzc3dvcmQxMjMh